engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpcodesniffer:
    enabled: true
    checks:
      Generic Files LineLength TooLong:
        enabled: false
      PSR2 Classes ClassDeclaration OpenBraceNewLine:
        enabled: false
      PSR2 Classes PropertyDeclaration Underscore:
        enabled: false
      Squiz Functions MultiLineFunctionDeclaration BraceOnSameLine:
        enabled: false
  phpmd:
    enabled: true
    checks:
      Naming/LongVariable:
        enabled: false
      CleanCode/BooleanArgumentFlag:
              enabled: false

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"

exclude_paths:
 - tests/
 - build/