engines:
  duplication:
    enabled: true
    config:
      languages:
      - php
  fixme:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD009:
        br_spaces: "2"
      MD013:
        linelength: "150"
      MD029:
        ol-prefix: "ordered"
  phan:
    enabled: true
    config:
      file_extensions: "php"
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Naming/LongVariable:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false

ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
  - "**.md"

exclude_paths:
 - tests/