# .travis.yml
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

install:
  - composer require satooshi/php-coveralls
    
script:
  - mkdir -p build/logs
  - phpunit -c phpunit.xml --coverage-text --verbose

after_success:
  - php coveralls.phar -v
  - php vendor/bin/coveralls -v