language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install
    
script:
  - mkdir -p build/logs
  - composer --version
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml --coverage-text --verbose

after_success:
  - php vendor/bin/coveralls -v