# .travis.yml
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  
matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
    
install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml --coverage-text --verbose

after_success:
  - travis_retry php vendor/bin/coveralls -v