# .travis.yml
language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

script:
  - phpunit --configuration phpunit.xml --coverage-text --verbose

after_script:
  - php vendor/bin/codacycoverage clover path/to/clover.xml